baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "iAMart"

[[menu.nav]]
    name = "home"
    url  = "/"
    weight = 1

[[menu.nav]]
    name = "art supply info"
    url  = "/articles"
    weight = 5