baseURL = "/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "iAMart"

[[menu.nav]]
    name = "home"
    url  = "/"
    weight = 1

[[menu.nav]]
    name = "stores"
    url  = "/content/stores"
    weight = 2

[[menu.nav]]
    name = "art supply info"
    url  = "/content/articles"
    weight = 5