baseURL = "/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "iAMart"

[[menu.nav]]
    name = "home"
    url  = "/"
    weight = 1

[[menu.nav]]
    name = "stores"
    url  = "/stores"
    weight = 2

[[menu.nav]]
    name = "join us"
    url  = "/join"
    weight = 3

[[menu.nav]]
    name = "vendors"
    url  = "/vendors"
    weight = 4

[[menu.nav]]
    name = "for artists"
    url  = "/articles"
    weight = 5