backend:
  name: git-gateway
  branch: master
  accept_roles: #optional - accepts all users if left out
    - admin
    - editor

media_folder: "static/images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/images/uploads" 

collections:
  - name: pages
    label: "Pages"
    files:
      - file: "content/home.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "content/stores/_index.md"
        label: "Stores Page - intro text"
        name: "stores"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "content/join.md"
        label: "Join Us"
        name: "join"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "content/vendors.md"
        label: "Vendors"
        name: "vendors"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "content/articles/_index.md"
        label: "Articles Page - intro text"
        name: "articles"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}

  - name: stores
    label: "Stores"
    folder: "content/stores/_stores"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Store Name", name: "title", widget: "string"}
      - {label: "Address", name: "address", widget: "string"}
      - {label: "City", name: "city", widget: "string"}
      - {label: "State", name: "state", widget: "string"}
      - {label: "Country", name: "country", widget: "select", options: ["United States", "Canada"]}
      - {label: "Phone (###-###-####)", name: "phone", widget: "string"}
      - {label: "Website (name to display, with .com", name: "website", widget: "string"}
      - {label: "URL (full web address beginning with http://www)", name: "weburl", widget: "string"}
      - {label: "E-commerce Switch ON for stores with online sales", name: "ecommerce", widget: "boolean", default: false}
      - {label: "type", name: "type", widget: "hidden", default: "stores"}

  - name: articles
    label: "Articles"
    folder: "content/articles/_articles"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Article Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Category", name: "category", widget: "list", default: ["drawing", "painting"]}
      - {label: "Article Picture", name: "picture", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "type", name: "type", widget: "hidden", default: "article"}

